### PR TITLE
Merge the recent master and drop a couple of `runQuoteT` calls

### PR DESCRIPTION
**Pull request by effectfully**
This merges the recent master into the `PR-PIR-generators` branch and [drops](https://github.com/Quviq/plutus/commit/d1f3e78e1ae586d1073f24a9cc9d488624d47d36) a couple of `runQuoteT` calls from it.

We can continue collaborating this way or you could give me write access to your fork.

### CODE REVIEW

**Comment by UlfNorell** [comment]
@effectfully I added you as a collaborator so you can update things directly.

**Comment by effectfully** [comment]
Thank you!

**Comment by effectfully** [comment]
@UlfNorell it doesn't seem like I'm allowed to push. Here's what I did:

```
$ git remote add Quviq https://github.com/Quviq/plutus
$ git push Quviq PR-PIR-generators 
remote: Permission to Quviq/plutus.git denied to effectfully.
fatal: unable to access 'https://github.com/Quviq/plutus/': The requested URL returned error: 403
```

Am I doing something wrong?

**Comment by UlfNorell** [comment]
You need to accept the invite:
Screenshot 2022-06-16 at 09 14 43

**Comment by effectfully** [comment]
Oh, sorry about that, it ended up in my "spam from GitHub" email folder.

**Comment by effectfully** [comment]
Closing this one, since I'll be committing directly to your branch.

**Pull request closed without merging**
